name: copycat_pro
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/raj457036/copycat_pro
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  copycat_base:
    path: ../copycat_base
  injectable: ^2.4.2
  get_it: ^7.7.0
  universal_io: ^2.2.2
  purchases_flutter: ^6.30.2
  purchases_ui_flutter: ^6.30.2
  retry: ^3.1.2
  supabase_flutter: ^2.5.8
  supabase_auth_ui:
    git:
      url: https://github.com/raj457036/flutter-auth-ui.git
  googleapis: ^13.1.0
  dartz: ^0.10.1
  url_launcher: ^6.3.0
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:  ^2.6.1
  build_runner: ^2.4.9
  freezed: 2.4.7

flutter: