name: copycat_pro
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/raj457036/copycat_pro
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  copycat_base:
    path: ../copycat_base
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  injectable: ^2.4.2
  get_it: ^7.7.0
  universal_io: ^2.2.2
  purchases_flutter: ^6.30.2
  purchases_ui_flutter: ^6.30.2
  retry: ^3.1.2
  supabase_flutter: ^2.5.8
  supabase_auth_ui:
    git:
      url: https://github.com/raj457036/flutter-auth-ui.git
  googleapis: ^13.1.0
  dartz: ^0.10.1
  url_launcher: ^6.3.0
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  super_clipboard: ^0.8.18
  super_drag_and_drop: ^0.8.18
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_core_desktop: ^1.0.2
  firebase_crashlytics: ^4.0.2
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:  ^2.6.1
  build_runner: ^2.4.9
  freezed: 2.4.7

dependency_overrides:
  firebase_core_platform_interface: ^5.1.0

flutter: